spring:
  profiles:
    active:
      - dev
---
spring:
  profiles:
    active: dev
  datasource:
#    mysql
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dev?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    #  默认使用Tomcat自带连接池
    maximum-pool-size: 50
    max-idle: 10
    max-wait: 5000
    min-idle: 10
    initial-size: 5
    validation-query: SELECT 1
    test-on-borrow: false
    test-while-idle: true
    time-between-eviction-runs-millis: 18800
---
spring:
  profiles: test  #测试环境
  application:
    name: microservicecloud-config-mky-test
#请保存为UTF-8格式